import { SalesRecord, InventoryItem, Customer } from "@/types";
import { PlaceHolderImages } from "./placeholder-images";

const avatar1 = PlaceHolderImages.find(p => p.id === "avatar-1")?.imageUrl || "";
const avatar2 = PlaceHolderImages.find(p => p.id === "avatar-2")?.imageUrl || "";
const avatar3 = PlaceHolderImages.find(p => p.id === "avatar-3")?.imageUrl || "";
const avatar4 = PlaceHolderImages.find(p => p.id === "avatar-4")?.imageUrl || "";
const avatar5 = PlaceHolderImages.find(p => p.id === "avatar-5")?.imageUrl || "";


export const mockSales: SalesRecord[] = [
    {
        id: "1",
        date: "2024-07-22T10:30:00Z",
        productName: "Premium Wireless Mouse",
        productId: "p1",
        quantity: 2,
        unitPrice: 2500,
        totalAmount: 5000,
        customerName: "Rahim Islam",
        customerId: "c1",
        paymentStatus: 'paid',
        customerAvatarUrl: avatar1,
    },
    {
        id: "2",
        date: "2024-07-22T11:00:00Z",
        productName: "Mechanical Keyboard",
        productId: "p2",
        quantity: 1,
        unitPrice: 8000,
        totalAmount: 8000,
        customerName: "Fatima Ahmed",
        customerId: "c2",
        paymentStatus: 'paid',
        customerAvatarUrl: avatar2,
    },
    {
        id: "3",
        date: "2024-07-21T15:00:00Z",
        productName: "USB-C Hub",
        productId: "p3",
        quantity: 5,
        unitPrice: 1500,
        totalAmount: 7500,
        customerName: "Karim Chowdhury",
        customerId: "c3",
        paymentStatus: 'pending',
        customerAvatarUrl: avatar3,
    },
    {
        id: "4",
        date: "2024-07-21T09:00:00Z",
        productName: "4K Webcam",
        productId: "p4",
        quantity: 1,
        unitPrice: 6500,
        totalAmount: 6500,
        customerName: "Ayesha Khan",
        customerId: "c4",
        paymentStatus: 'paid',
        customerAvatarUrl: avatar4,
    },
    {
        id: "5",
        date: "2024-07-20T18:00:00Z",
        productName: "Laptop Stand",
        quantity: 3,
        unitPrice: 2200,
        totalAmount: 6600,
        customerName: "Jamil Hasan",
        customerId: "c5",
        paymentStatus: 'partial',
        customerAvatarUrl: avatar5,
    },
     {
        id: "6",
        date: "2024-06-15T10:00:00Z",
        productName: "Premium Wireless Mouse",
        productId: "p1",
        quantity: 1,
        unitPrice: 2500,
        totalAmount: 2500,
        customerName: "Rahim Islam",
        customerId: "c1",
        paymentStatus: 'paid',
        customerAvatarUrl: avatar1,
    },
    {
        id: "7",
        date: "2024-05-30T14:20:00Z",
        productName: "Mechanical Keyboard",
        productId: "p2",
        quantity: 1,
        unitPrice: 8000,
        totalAmount: 8000,
        customerName: "Ayesha Khan",
        customerId: "c4",
        paymentStatus: 'paid',
        customerAvatarUrl: avatar4,
    }
];

export const mockInventory: InventoryItem[] = [
    {
        id: "p1",
        productName: "Premium Wireless Mouse",
        currentStock: 15,
        unit: "pcs",
        reorderLevel: 10,
        costPrice: 1800,
        sellingPrice: 2500,
        status: 'ok',
    },
    {
        id: "p2",
        productName: "Mechanical Keyboard",
        currentStock: 5,
        unit: "pcs",
        reorderLevel: 8,
        costPrice: 6000,
        sellingPrice: 8000,
        status: 'low',
    },
    {
        id: "p3",
        productName: "USB-C Hub",
        currentStock: 50,
        unit: "pcs",
        reorderLevel: 20,
        costPrice: 1000,
        sellingPrice: 1500,
        status: 'ok',
    },
    {
        id: "p4",
        productName: "4K Webcam",
        currentStock: 8,
        unit: "pcs",
        reorderLevel: 5,
        costPrice: 5000,
        sellingPrice: 6500,
        status: 'ok',
    },
    {
        id: "p5",
        productName: "Ergonomic Chair",
        currentStock: 30,
        unit: "pcs",
        reorderLevel: 15,
        costPrice: 12000,
        sellingPrice: 18000,
        status: 'overstock',
    }
];

export const mockCustomers: Customer[] = [
    {
        id: "c1",
        name: "Rahim Islam",
        email: "rahim@example.com",
        firstPurchase: "2024-01-10",
        lastPurchase: "2024-07-22",
        totalPurchases: 5,
        totalSpent: 25000,
        averageOrderValue: 5000,
    },
    {
        id: "c2",
        name: "Fatima Ahmed",
        email: "fatima@example.com",
        firstPurchase: "2024-05-20",
        lastPurchase: "2024-07-22",
        totalPurchases: 2,
        totalSpent: 16000,
        averageOrderValue: 8000,
    },
    {
        id: "c3",
        name: "Karim Chowdhury",
        email: "karim@example.com",
        firstPurchase: "2023-11-05",
        lastPurchase: "2024-03-15",
        totalPurchases: 8,
        totalSpent: 45000,
        averageOrderValue: 5625,
    },
    {
        id: "c4",
        name: "Ayesha Khan",
        email: "ayesha@example.com",
        firstPurchase: "2024-02-18",
        lastPurchase: "2024-07-21",
        totalPurchases: 12,
        totalSpent: 95000,
        averageOrderValue: 7916,
    },
    {
        id: "c5",
        name: "Jamil Hasan",
        email: "jamil@example.com",
        firstPurchase: "2024-06-01",
        lastPurchase: "2024-06-20",
        totalPurchases: 3,
        totalSpent: 11000,
        averageOrderValue: 3667,
    },
];
