
'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'bn';

type Translations = {
    [key in Language]: {
        [key: string]: any;
    };
};

export const strings: Translations = {
    en: {
        dashboard: 'Dashboard',
        salesForecasting: 'Sales Forecasting',
        inventory: 'Inventory',
        cashFlow: 'Cash Flow',
        customers: 'Customers',
        reports: 'Reports',
        aiAgent: 'AI Agent',
        settings: 'Settings',
        search: 'Search',
        appSlogan: 'Transforming your business data into actionable insights. AI-powered analytics for Bangladeshi SMEs.',
        loginTitle: 'Login',
        loginDescription: 'Enter your email below to login to your account',
        emailLabel: 'Email',
        passwordLabel: 'Password',
        forgotPasswordLink: 'Forgot your password?',
        loginButton: 'Login',
        signupPrompt: "Don't have an account?",
        signupLink: 'Sign up',
        loginSuccess: 'Login Successful',
        welcomeBack: 'Welcome back!',
        welcomeAdmin: 'Welcome, Admin!',
        loginFailed: 'Login Failed',
        invalidCredentials: 'Invalid email or password. Please try again.',
        adminAuthFailed: 'Admin Authentication Failed',
        invalidAdminCredentials: 'The admin credentials you entered are incorrect.',
        signupFailed: 'Signup Failed',
        passwordsDoNotMatch: "Passwords do not match.",
        signupSuccess: 'Signup Successful',
        userCreatedSuccessfully: 'The new user account has been created.',
        error: 'Error',
        emailNotRegistered: 'This email is not registered.',
        passwordResetFailed: 'Password Reset Failed',
        passwordResetSuccess: 'Password Reset Successful',
        passwordUpdatedSuccessfully: 'Your password has been updated. You can now log in with your new password.',
        adminAuthentication: 'Admin Authentication',
        enterAdminCredentials: 'Please enter admin credentials to proceed with user creation.',
        authenticate: 'Authenticate',
        createNewUser: 'Create New User',
        enterNewUserDetails: 'Enter the details for the new user account.',
        confirmPassword: 'Confirm Password',
        createUser: 'Create User',
        enterEmailToReset: 'Enter your registered email address to receive a password reset link.',
        findAccount: 'Find Account',
        resetPassword: 'Reset Password',
        newPassword: 'New Password',
        enterNewPasswordFor: (email: string) => `Enter a new password for ${email}.`,
        totalRevenue: 'Total Revenue',
        totalRevenueDescription: '+20.1% from last month',
        activeCustomers: 'Active Customers',
        activeCustomersDescription: '+180.1% from last month',
        stockValue: 'Stock Value',
        stockValueDescription: 'Total value of current inventory',
        pendingPayments: 'Pending Payments',
        pendingPaymentsDescription: 'From 12 invoices',
        salesOverview: 'Sales Overview',
        salesOverviewDescription: 'An overview of your sales for the selected year.',
        recentSales: 'Recent Sales',
        recentSalesDescription: (count: number) => `You made ${count} sales this month.`,
        inventoryAlerts: 'Inventory Alerts',
        inventoryAlertsDescription: 'Items that need your attention.',
        inventoryAlertsEmpty: 'All inventory levels are looking good!',
        lowStock: 'Low Stock',
        overstock: 'Overstock',
        agentTitle: "AI Business Agent",
        agentDescription: "Chat with your AI assistant to get business insights and suggestions.",
        agentInitialMessage: "Welcome! I'm SmartBiz Lite AI. How can I help you analyze your business today? You can ask me about sales, inventory, customers, or for general advice.",
        agentInputPlaceholder: "Ask about sales, inventory, or customers...",
        agentRequestFailed: "Request Failed",
        agentErrorConnecting: "Sorry, I'm having trouble connecting. Please try again later.",
        cashflowTitle: "Cash Flow Analytics",
        cashflowDescription: "Track your income, expenses, and cash flow projections.",
        analyzeCashFlow: "Analyze Cash Flow",
        currentCashPosition: "Current Cash Position",
        thirtyDayProjection: "30-Day Projection",
        upcomingShortfalls: "Upcoming Shortfalls",
        paymentCycleAnalysis: "Payment Cycle Analysis",
        expensePatternIdentification: "Expense Pattern Identification",
        customersTitle: "Customer Insights",
        customersDescription: "Segment your customers and get retention insights.",
        analyzeCustomers: "Analyze Customers",
        customerList: "Customer List",
        customerListDescriptionWithSegments: "Customer segments have been updated.",
        customerListDescription: "Showing all customers.",
        customerName: "Name",
        totalSpent: "Total Spent",
        lastPurchase: "Last Purchase",
        segment: "Segment",
        forecastTitle: "Sales Forecasting",
        forecastDescription: "Use AI to predict future sales and identify trends based on your historical data.",
        generate30DayForecast: "Generate 30-Day Forecast",
        productForecast: "Product Forecast",
        productForecastDescription: "Predicted sales for the next 30 days.",
        product: "Product",
        predictedSales: "Predicted Sales",
        confidence: "Confidence",
        trend: "Trend",
        aiInsights: "AI Insights",
        aiRecommendations: "AI Recommendations",
        actionItems: "Action Items",
        inventoryTitle: "Inventory Management",
        inventoryDescription: "Manage your stock and get AI-powered reorder recommendations.",
        addNewItem: "Add New Item",
        getAIRecommendations: "Get AI Recommendations",
        currentInventory: "Current Inventory",
        currentInventoryDescription: "An overview of all items in your inventory.",
        reportsTitle: "Automated Reports",
        reportsDescription: "Generate and download weekly or monthly business performance reports.",
        generateReport: "Generate Report",
        weeklyReport: "Weekly Report",
        monthlyReport: "Monthly Report",
        generatedReportTitle: (period: string) => `Generated ${period.charAt(0).toUpperCase() + period.slice(1)} Report`,
        settingsTitle: "Settings",
        settingsDescription: "Manage your account and application preferences.",
        settingsNotImplemented: "Settings page will be implemented here.",
        logout: "Logout",
    },
    bn: {
        dashboard: 'ড্যাশবোর্ড',
        salesForecasting: 'বিক্রয় পূর্বাভাস',
        inventory: 'ইনভেন্টরি',
        cashFlow: 'নগদ প্রবাহ',
        customers: 'গ্রাহক',
        reports: 'রিপোর্ট',
        aiAgent: 'এআই এজেন্ট',
        settings: 'সেটিংস',
        search: 'অনুসন্ধান',
        appSlogan: 'আপনার ব্যবসার ডেটাকে কার্যকরী অন্তর্দৃষ্টিতে রূপান্তর করা। বাংলাদেশী এসএমই-এর জন্য এআই-চালিত বিশ্লেষণ।',
        loginTitle: 'লগইন',
        loginDescription: 'আপনার অ্যাকাউন্টে লগইন করতে নিচে আপনার ইমেল লিখুন',
        emailLabel: 'ইমেল',
        passwordLabel: 'পাসওয়ার্ড',
        forgotPasswordLink: 'পাসওয়ার্ড ভুলে গেছেন?',
        loginButton: 'লগইন',
        signupPrompt: 'আপনার কি কোনো অ্যাকাউন্ট নেই?',
        signupLink: 'সাইন আপ',
        loginSuccess: 'লগইন সফল',
        welcomeBack: 'আপনাকে আবার স্বাগতম!',
        welcomeAdmin: 'স্বাগতম, অ্যাডমিন!',
        loginFailed: 'লগইন ব্যর্থ',
        invalidCredentials: 'ভুল ইমেল বা পাসওয়ার্ড। আবার চেষ্টা করুন.',
        adminAuthFailed: 'অ্যাডমিন প্রমাণীকরণ ব্যর্থ',
        invalidAdminCredentials: 'আপনি যে অ্যাডমিন প্রমাণপত্র দিয়েছেন তা ভুল।',
        signupFailed: 'সাইন আপ ব্যর্থ',
        passwordsDoNotMatch: "পাসওয়ার্ড মিলছে না।",
        signupSuccess: 'সাইন আপ সফল',
        userCreatedSuccessfully: 'নতুন ব্যবহারকারী অ্যাকাউন্ট তৈরি করা হয়েছে।',
        error: 'ত্রুটি',
        emailNotRegistered: 'এই ইমেলটি নিবন্ধিত নয়।',
        passwordResetFailed: 'পাসওয়ার্ড রিসেট ব্যর্থ',
        passwordResetSuccess: 'পাসওয়ার্ড রিসেট সফল',
        passwordUpdatedSuccessfully: 'আপনার পাসওয়ার্ড আপডেট করা হয়েছে। আপনি এখন আপনার নতুন পাসওয়ার্ড দিয়ে লগইন করতে পারেন।',
        adminAuthentication: 'অ্যাডমিন প্রমাণীকরণ',
        enterAdminCredentials: 'ব্যবহারকারী তৈরির জন্য অনুগ্রহ করে অ্যাডমিন প্রমাণপত্র লিখুন।',
        authenticate: 'প্রমাণীকরণ',
        createNewUser: 'নতুন ব্যবহারকারী তৈরি করুন',
        enterNewUserDetails: 'নতুন ব্যবহারকারী অ্যাকাউন্টের জন্য বিবরণ লিখুন।',
        confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
        createUser: 'ব্যবহারকারী তৈরি করুন',
        enterEmailToReset: 'পাসওয়ার্ড রিসেট লিঙ্ক পেতে আপনার নিবন্ধিত ইমেল ঠিকানা লিখুন।',
        findAccount: 'অ্যাকাউন্ট খুঁজুন',
        resetPassword: 'পাসওয়ার্ড রিসেট করুন',
        newPassword: 'নতুন পাসওয়ার্ড',
        enterNewPasswordFor: (email: string) => `${email}-এর জন্য একটি নতুন পাসওয়ার্ড লিখুন।`,
        totalRevenue: 'মোট রাজস্ব',
        totalRevenueDescription: 'গত মাস থেকে +২০.১%',
        activeCustomers: 'সক্রিয় গ্রাহক',
        activeCustomersDescription: 'গত মাস থেকে +১৮০.১%',
        stockValue: 'স্টকের মূল্য',
        stockValueDescription: 'বর্তমান ইনভেন্টরির মোট মূল্য',
        pendingPayments: 'মুলতুবি পেমেন্ট',
        pendingPaymentsDescription: '১২টি চালান থেকে',
        salesOverview: 'বিক্রয় সারসংক্ষেপ',
        salesOverviewDescription: 'নির্বাচিত বছরের জন্য আপনার বিক্রয়ের একটি সারসংক্ষেপ।',
        recentSales: 'সাম্প্রতিক বিক্রয়',
        recentSalesDescription: (count: number) => `এই মাসে আপনি ${count}টি বিক্রয় করেছেন।`,
        inventoryAlerts: 'ইনভেন্টরি সতর্কতা',
        inventoryAlertsDescription: 'যে আইটেমগুলিতে আপনার মনোযোগ প্রয়োজন।',
        inventoryAlertsEmpty: 'ইনভেন্টরির সব স্তর ঠিক আছে!',
        lowStock: 'কম স্টক',
        overstock: 'অতিরিক্ত স্টক',
        agentTitle: "এআই বিজনেস এজেন্ট",
        agentDescription: "ব্যবসার অন্তর্দৃষ্টি ও পরামর্শ পেতে আপনার এআই সহকারীর সাথে কথা বলুন।",
        agentInitialMessage: "স্বাগতম! আমি স্মার্টবিজ লাইট এআই। আজ আপনার ব্যবসা বিশ্লেষণে আমি কীভাবে সাহায্য করতে পারি? আপনি আমাকে বিক্রয়, ইনভেন্টরি, গ্রাহক বা সাধারণ পরামর্শ সম্পর্কে জিজ্ঞাসা করতে পারেন।",
        agentInputPlaceholder: "বিক্রয়, ইনভেন্টরি, বা গ্রাহক সম্পর্কে জিজ্ঞাসা করুন...",
        agentRequestFailed: "অনুরোধ ব্যর্থ হয়েছে",
        agentErrorConnecting: "দুঃখিত, সংযোগ করতে সমস্যা হচ্ছে। অনুগ্রহ করে পরে আবার চেষ্টা করুন।",
        cashflowTitle: "নগদ প্রবাহ বিশ্লেষণ",
        cashflowDescription: "আপনার আয়, ব্যয় এবং নগদ প্রবাহের পূর্বাভাস ট্র্যাক করুন।",
        analyzeCashFlow: "নগদ প্রবাহ বিশ্লেষণ করুন",
        currentCashPosition: "বর্তমান নগদ অবস্থা",
        thirtyDayProjection: "৩০-দিনের পূর্বাভাস",
        upcomingShortfalls: "আসন্ন ঘাটতি",
        paymentCycleAnalysis: "পেমেন্ট চক্র বিশ্লেষণ",
        expensePatternIdentification: "ব্যয়ের ধরন শনাক্তকরণ",
        customersTitle: "গ্রাহক অন্তর্দৃষ্টি",
        customersDescription: "আপনার গ্রাহকদের ভাগ করুন এবং তাদের ধরে রাখার অন্তর্দৃষ্টি পান।",
        analyzeCustomers: "গ্রাহকদের বিশ্লেষণ করুন",
        customerList: "গ্রাহক তালিকা",
        customerListDescriptionWithSegments: "গ্রাহক বিভাগগুলি আপডেট করা হয়েছে।",
        customerListDescription: "সমস্ত গ্রাহকদের দেখানো হচ্ছে।",
        customerName: "নাম",
        totalSpent: "মোট ব্যয়",
        lastPurchase: "শেষ ক্রয়",
        segment: "সেগমেন্ট",
        forecastTitle: "বিক্রয় পূর্বাভাস",
        forecastDescription: "আপনার অতীত ডেটার উপর ভিত্তি করে ভবিষ্যতের বিক্রয় পূর্বাভাস এবং প্রবণতা শনাক্ত করতে এআই ব্যবহার করুন।",
        generate30DayForecast: "৩০-দিনের পূর্বাভাস তৈরি করুন",
        productForecast: "পণ্যের পূর্বাভাস",
        productForecastDescription: "আগামী ৩০ দিনের জন্য পূর্বাভাসিত বিক্রয়।",
        product: "পণ্য",
        predictedSales: "পূর্বাভাসিত বিক্রয়",
        confidence: "আত্মবিশ্বাস",
        trend: "প্রবণতা",
        aiInsights: "এআই অন্তর্দৃষ্টি",
        aiRecommendations: "এআই সুপারিশ",
        actionItems: "করণীয়",
        inventoryTitle: "ইনভেন্টরি ম্যানেজমেন্ট",
        inventoryDescription: "আপনার স্টক পরিচালনা করুন এবং এআই-চালিত পুনঃরায় অর্ডারের সুপারিশ পান।",
        addNewItem: "নতুন আইটেম যোগ করুন",
        getAIRecommendations: "এআই সুপারিশ পান",
        currentInventory: "বর্তমান ইনভেন্টরি",
        currentInventoryDescription: "আপনার ইনভেন্টরিতে থাকা সমস্ত আইটেমের একটি সংক্ষিপ্ত বিবরণ।",
        reportsTitle: "স্বয়ংক্রিয় রিপোর্ট",
        reportsDescription: "সাপ্তাহিক বা মাসিক ব্যবসায়িক কর্মক্ষমতা রিপোর্ট তৈরি এবং ডাউনলোড করুন।",
        generateReport: "রিপোর্ট তৈরি করুন",
        weeklyReport: "সাপ্তাহিক রিপোর্ট",
        monthlyReport: "মাসিক রিপোর্ট",
        generatedReportTitle: (period: string) => `${period === 'weekly' ? 'সাপ্তাহিক' : 'মাসিক'} রিপোর্ট তৈরি হয়েছে`,
        settingsTitle: "সেটিংস",
        settingsDescription: "আপনার অ্যাকাউন্ট এবং অ্যাপ্লিকেশন পছন্দগুলি পরিচালনা করুন।",
        settingsNotImplemented: "সেটিংস পৃষ্ঠাটি 여기 প্রয়োগ করা হবে।",
        logout: "লগআউট",
    },
};

interface LanguageContextProps {
    language: Language;
    setLanguage: (language: Language) => void;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>('en');

    return (
        <LanguageContext.Provider value={{ language, setLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
